
import './common-widgets/check-button.js'
import './common-widgets/choice-buttons.js'
import './common-widgets/color-combo.js'
import './common-widgets/combo.js'
import './common-widgets/email-input.js'
import './common-widgets/labels.js'
import './common-widgets/numeric-input.js'
import './common-widgets/password-input.js'
import './common-widgets/phone-input.js'
import './common-widgets/progress-disc.js'
import './common-widgets/push-button.js'
import './common-widgets/slider.js'
import './common-widgets/text-input.js'
import './common-widgets/up-down.js'
