name: CI

on: push

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
      - run: npx eslint js
