name: Code Quality

on:
  push:
    branches:
      - master
      - dev
      - feature-*
      - improvement-*
      - fix-*
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@master
      - name: Node Setup
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '10.x'
      - name: Parse Ref
        id: parse_ref
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=SOURCE_VERSION::${GITHUB_REF#refs/tags/version-}
      - name: Update Source Version
        run: sed -i "s/unknown-version/${{ steps.parse_ref.outputs.SOURCE_VERSION }}/" package.json
      - name: Install Dev Deps
        run: npm install --only=dev
      - name: ESLint
        run: npx eslint js
