name: Publish

on:
  push:
    tags:
      - version-*

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: '10.x'
      - run: npx eslint js
  jsdoc:
    name: Publish Docs
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@master
      - uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs
          BUILD_SCRIPT: npm install && rm -rf docs/* js/lib/* && npx jsdoc -c jsdoc.conf.json
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs:
      - lint
      - jsdoc
    steps:
      - uses: actions/checkout@master
      - run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
